### ISSUE TITLE
no suitable terraform binary could be found

### ISSUE THREAD

**Issue by pmcdonald-metropolis** [rootsami/terradrift#14]
Getting the following error when I run terradrift-cli

OS: MacOS 13.2 - M1

terraform path:
```
which terraform
/opt/homebrew/bin/terraform
```
terradrift-cli --workdir="./stacks"
```
ERRO[0000] running NewTerraform: no suitable terraform binary could be found: NewTerraform: please supply the path to a Terraform executable using execPath, e.g. using the github.com/hashicorp/hc-install module.
```

**Comment by rootsami** [comment]
most probably terraform version is not defined in your tf files. for example:
```tf
terraform {
  required_version = ">= 1.0.6"
}
```

I agree, Error should be handled in a better way to suggest similar actions. I'll create an issue for that

**Comment by rootsami** [comment]
Also, I would strongly recommend using  [v0.0.3](https://github.com/rootsami/terradrift/releases/tag/v0.0.3), the current latest release as there's a critical bug fix 👍
